Cluster contextualization
cernvm/cernvm-micro pull request #8
Opened 2017-01-17 10:49 UTC by pejirout

User may optionally provide additional information in the 'ucernvm'
section of the context file to use a master/slave cluster
contextualization.

Master sends its IP address to the central service (cernvm-online.cern.ch),
from where it is fetched by the slave machines. The slave machines
are waiting for the master to publish the data (blocking wait in the
bootloader).

2017-01-17 13:15 UTC, jblomer requested changes
Nice!  Besides the inline comments:

  - I think there is enough code to justify another snippet, e.g. 08clustercontext
  - The parsing of the [ucernvm-begin]..[ucernvm-end] block has been already done.  All the variables in this block are available as bash environment variables `_UCONTEXT_<VARIABLE NAME>`.  See for instance 14cvmfs.
  - I guess you didn't try this yet with an HTTPS URL, right?  I think we need to add a CA directory to the image that curl then picks up for HTTPS verification.

2017-01-17 13:15 UTC, jblomer commented on scripts.d/06context
> +    if [ "x$master_field" = "xtrue" -o "x$master_field" = "xTrue" -o "x$master_field" = "x1" -o "x$master_field" = "xyes" ]; then
This can become a utility function in runtime-init.sh, like `IsOn`

2017-01-17 13:15 UTC, jblomer commented on scripts.d/06context
> +    local CURL_CMD="$CURL_CMD_TEMPLATE $SERVICE_URL/api/clusters/$CLUSTER_PIN/keys/$READY_STATUS_KEY_FIELD $CURL_HEADERS"
I think the API should have a version component, like `.../api/v1/clusters/...`

2017-01-17 13:15 UTC, jblomer commented on scripts.d/06context
> +    while [ $cnt -lt $MAX_TRIES ]; do
Making a curl request can become a function, I think it is the same code as further down.

2017-01-17 13:15 UTC, jblomer commented on scripts.d/06context
> +    log_start "Replaced the IP placeholder with: $masterIp"
This logline should additionally be added to /var/log/context.log

2017-01-17 13:15 UTC, jblomer commented on scripts.d/06context
> +    INTERFACE_NAME=$( $BBOX ifconfig | head -n 1 | cut -d: -f1 | awk '{print $1}' )
Isn't there already an ifconfig symlink to busybox present?

2017-01-17 13:24 UTC, pejirout commented on scripts.d/06context
> +    INTERFACE_NAME=$( $BBOX ifconfig | head -n 1 | cut -d: -f1 | awk '{print $1}' )
It is, but I want to be sure I'm using the busybox ifconfig version. The system default ifconfig is producing a slightly different output format, which is a problem for us, because we need to parse the output. Here it should work fine, I just want to make that explicit.

2017-01-17 13:24 UTC, pejirout commented on scripts.d/06context
> +    local CURL_CMD="$CURL_CMD_TEMPLATE $SERVICE_URL/api/clusters/$CLUSTER_PIN/keys/$READY_STATUS_KEY_FIELD $CURL_HEADERS"
Ok, will do.

2017-01-17 13:25 UTC, jblomer commented on scripts.d/06context
> +    INTERFACE_NAME=$( $BBOX ifconfig | head -n 1 | cut -d: -f1 | awk '{print $1}' )
OK

2017-01-17 13:42 UTC, pejirout commented on scripts.d/06context
> +    log_start "Replaced the IP placeholder with: $masterIp"
Ok.

2017-01-17 14:33 UTC, pejirout commented on scripts.d/06context
> +    while [ $cnt -lt $MAX_TRIES ]; do
It is, except in the second case we also need the get the response (not just the  status code). Because we cannot return two values from a function, then we would need to create yet another function to abstract it away, which I thought would be quite cumbersome.

Do you still want a special function for that?

2017-01-17 14:35 UTC, jblomer commented on scripts.d/06context
> +    while [ $cnt -lt $MAX_TRIES ]; do
Hm, perhaps code and ouput can be combined somehow.  For instance, first line status code, rest output.

2017-01-19 09:06 UTC, pejirout commented
Trying to use curl with HTTPS in the bootloader phase is failing:
`Protocol https not supported or disabled in libcurl`

2017-01-23 16:08 UTC, merged